// src/components/layouts/BaseHead.tsx
import Head from "next/head"
import { useRouter } from "next/router"
import { BaseHeadProps } from "@/models/Interfaces"

export default function BaseHead({ title, description, img }: BaseHeadProps) {
  const router = useRouter()
  const SITE_TITLE = "Art & Biro"
  const INDEX_TITLE = "Art & Biro Index"
  const INDEX_DESC = "Index desc"
  const GLOBAL_TITLE = `${title} | ${SITE_TITLE}`
  const tags = ["test", "op", "yeet"]
  return (
    <Head>
      <title>{router.pathname == "/" ? INDEX_TITLE : GLOBAL_TITLE}</title>
      <link rel="canonical" href={`https://localhost:3000${router.asPath}`} />
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta
        name="description"
        content={router.pathname == "/" ? INDEX_DESC : description}
      />
      <meta name="keywords" content={tags?.join(", ")} />

      {/* Open Graph */}
      <meta property="og:type" content="website" />
      <meta
        property="og:url"
        content={`https://localhost:3000${router.asPath}`}
      />
      <meta property="og:image" content={img} />
      <meta
        property="og:title"
        content={router.pathname === "/" ? INDEX_TITLE : GLOBAL_TITLE}
      />
      <meta
        property="og:description"
        content={router.pathname === "/" ? INDEX_DESC : description}
      />

      {/* Twitter Card */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta
        name="twitter:title"
        content={router.pathname === "/" ? INDEX_TITLE : GLOBAL_TITLE}
      />
      <meta
        name="twitter:url"
        content={`https://localhost:3000${router.asPath}`}
      />
      <meta
        name="twitter:description"
        content={router.pathname === "/" ? INDEX_DESC : description}
      />
      <meta name="twitter:image" content={img} />
    </Head>
  )
}

// components/BaseHead.vue
<script setup lang="ts">
const props = defineProps<{
  title?: string;
  description?: string;
  keywords?: string[];
  img?: string;
  isDefaultIndex?: boolean;
}>()

const SITE_TITLE = ref("Art and Biro");

const indexTitle = ref("Art and Biro");
const indexDescription = ref("It's working wow");

</script>

<template>
  <Head>
    <!-- isDefaultIndex truthy -->
    <Title v-if="isDefaultIndex === true">{{ indexTitle }}</Title>
    <Meta v-if="isDefaultIndex === true" name="title" :content="indexTitle" />
    <Meta v-if="isDefaultIndex === true" name="description" :content="indexDescription" />
    <Meta v-if="isDefaultIndex === true" property="og:title" :content="indexTitle" />
    <Meta v-if="isDefaultIndex === true" property="og:description" :content="indexDescription" />
    <Meta v-if="isDefaultIndex === true" name="twitter:title" :content="indexTitle" />
    <Meta v-if="isDefaultIndex === true" name="twitter:description" :content="indexDescription" />

    <!-- isDefaultIndex falsy -->
    <Title v-else>{{ title }} - {{ SITE_TITLE }}</Title>
    <Meta v-else name="description" :content="description" />
    <Meta v-else name="title" :content="`${title} - ${SITE_TITLE}`" />
    <Meta v-else property="og:title" :content="`${title} - ${SITE_TITLE}`" />
    <Meta v-else property="og:description" :content="description" />
    <Meta v-else name="twitter:title" :content="`${title} - ${SITE_TITLE}`" />
    <Meta v-else name="twitter:description" :content="description" />

    <!-- No change -->
    <Meta v-if="keywords" name="keywords" :content="keywords?.join(', ')" />
    <Meta v-if="img" name="image" :content="img" />
    <Meta property="og:type" content="website" />
    <Meta v-if="img" property="og:image" :content="img" />
    <Meta name="twitter:card" content="summary_large_image" />
    <Meta v-if="img" name="twitter:image" :content="img" />
  </Head>
</template>
